name: ci-java-workflow
on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - master
jobs: 
  check-application:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [11, 17, 21]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          java-package: jdk
          distribution: 'temurin'

      - name: Run Java application
        run: java teste1